project_id = "refncwnbaiudqhjohdeb"

[functions.generate-contract]
verify_jwt = false

[functions.realtime-voice]
verify_jwt = false

[functions.realtime-session]
verify_jwt = false

[functions.elevenlabs-session]
verify_jwt = false
